name: Hermes Action

on: 
  push:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs: 
  stable:
    name: Stable Rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Install clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: cargo test --verbose
      
  nightly:
    name: Nightly Rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@v1
      - name: Build
        run: cargo +nightly build --verbose
      #    - name: Install clippy
      #      run: rustup component add clippy
      #    - name: Run clippy
      #      run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: cargo +nightly test --verbose
